name: Chrome
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    environment: dev
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          env: true
          build: npm run build
          start: npm start
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ec2-user
          TARGET: webAPP